[phases.setup]
nixPkgs = ['nodejs_18', 'openssl_3_0', 'pkg-config']

[phases.install]
cmds = [
    'npm ci --omit=dev',
    'npx prisma generate'
]

[phases.build]
cmds = ['npm run railway:build']

[start]
cmd = 'npm run railway:start'

[variables]
PRISMA_CLI_BINARY_TARGETS = "linux-musl-openssl-3.0.x"
OPENSSL_CONF = "/dev/null"